//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SendGridEventsModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public string smtpID { get; set; }
        public string Email { get; set; }
        public string Event1 { get; set; }
        public string Category { get; set; }
        public string UniqueArguments { get; set; }
        public string Response { get; set; }
        public Nullable<int> Attempt { get; set; }
        public string Reason { get; set; }
        public string UserAgent { get; set; }
        public string IP { get; set; }
        public string URL { get; set; }
        public string Status { get; set; }
        public string BounceType { get; set; }
        public int ID { get; set; }
        public int JobID { get; set; }
        public System.DateTime EventDate { get; set; }
    }
}
